on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
          monorepo-tags: true

      - name: Dump
        env:
          ELEMENT_DIR: ${{ steps.release.outputs.paths_released }}
        run: echo ${ELEMENT_DIR} | tr -d '[]"'

      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.releases_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build and publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          ELEMENT_PATHS: ${{ steps.release.outputs.paths_released }}
        run: |
          for path in `echo ${ELEMENT_PATHS//,/ } | tr -d '[]"'`
          do \
          cd $path && \
          npm run build && \
          npm publish --dry-run && \
          cd ../../
          done
        if: ${{ steps.release.outputs.releases_created }}
